version: '3.4'

services:
  catalogdb:
    container_name: catalogdb # name of the container
    restart: always # on failure, restart the container
    ports:
      - "27017:27017" # expose port 27017 from the container to the host
    volumes:
      - mongo_data:/data/db # mongo data volume mount point 
  
  basketdb:
    container_name: basketdb # name of the container
    restart: always # on failure, restart the container
    ports:
      - "6379:6379" # expose port 27017 from the container to the host

  discountdb:
    container_name: discountdb # name of the container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always # on failure, restart the container
    ports:
      - "5432:5432" # expose port 27017 from the container to the host
    volumes:
      - postgres_data:/var/lib/postgresql/data # postgres data volume mount point

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=birkan@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalogapi:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb # run db before api
    ports:
      - "8000:80" # expose port 80 from the container to the host

  basketapi:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb # run db before api
    ports:
      - "8001:80"


  discountapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb # run db before api
    ports:
      - "8002:80"

